### ISSUE TITLE
Is ACCESS_BACKGROUND_LOCATION permission really needed?

### ISSUE THREAD

**Issue by dononcharles** [LeandroSQ/android-ble-made-easy#12]
Hi,
Would not be better to remove this permission (ACCESS_BACKGROUND_LOCATION) from the manifest file ?

Without ACCESS_BACKGROUND_LOCATION permission, the scanning works. 
According to Google doc [BACKGROUND PERMISSION](https://developer.android.com/training/location/background#evaluate) if ACCESS_BACKGROUND_LOCATION is not relevant, it can be removed.

Thanks

**Comment by LeandroSQ** [comment]
Hello there, sorry for the delay 
I somehow managed to miss this completelly.

The background location, is actually [required on Android 10+ when the scanning happens on a service](https://developer.android.com/guide/topics/connectivity/bluetooth/permissions#discover-local-devices) (Even on foreground services). 

**If not used in services and in Android 10+, this permission is not necessary.**

We can probably make a better job on the readme.md explaning this use case.
