### ISSUE TITLE
MTU size request

### ISSUE THREAD

**Issue by Octavelscx** [LeandroSQ/android-ble-made-easy#25]
Hi there it's me again,

I'm trying to receive data from a notify characteristic, it works perfectly but I only receive 20 bytes when I'm supposed to get 50.

After some research I found that it may be the MTU size :

https://stackoverflow.com/questions/69905359/reading-more-than-20-bytes-in-android-ble
https://punchthrough.com/maximizing-ble-throughput-part-2-use-larger-att-mtu-2/
https://developer.android.com/reference/android/bluetooth/BluetoothGatt.html#requestMtu(int)

It may be my device but I would be sure it's not other thing, so I would like to call requestMtu() but don't have any idea how to do that with your library...

If you have any idea :) 

Thanks again!

**Comment by LeandroSQ** [comment]
Hello there, thank you for this feature request.
I will study the possibility of adding this in the library in the near future.

Is this only for reading? Or is it required for writing too?

**Comment by Octavelscx** [comment]
Nice, only for reading I think

**Comment by LeandroSQ** [comment]
v1.8.2 ships with this :)

**Comment by LeandroSQ** [comment]
v1.8.2 is out, it includes this.
Thanks @valexi7
