### ISSUE TITLE
version 1.9.0 not published

### ISSUE THREAD

**Issue by miladheydari** [LeandroSQ/android-ble-made-easy#44]
Hi,
version 1.9.0 not published on jitpack
<img width="665" alt="Screenshot 1402-08-08 at 3 21 04 in the afternoon" src="https://github.com/LeandroSQ/android-ble-made-easy/assets/13203029/26f2a1ae-bdaa-44e7-a4e5-93dc8207e836">

**Comment by LeandroSQ** [comment]
First of all, thank you for pointing it out!

I totally missed this, thank you!

**Comment by automech** [comment]
hi is this still getting added? thanks

**Comment by LeandroSQ** [comment]
Hello, yes.
I'm sorry for the general delay but life has been crazy. 

It seems to be an issue around the multi-dex.

**Comment by LeandroSQ** [comment]
Published 1.9.1 solving the issue :)
