### ISSUE TITLE
Broken link in README.md

### ISSUE THREAD

**Issue by oliverdaisey** [LeandroSQ/android-ble-made-easy#45]
https://github.com/LeandroSQ/android-ble-made-easy?tab=readme-ov-file#sample-app

The section describing the Sample App contains a link to a directory that does not exist anymore
https://github.com/LeandroSQ/android-ble-made-easy/tree/master/app/src/main/java/quevedo/soares/leandro/blemadeeasy/view.

**Comment by LeandroSQ** [comment]
Thank you for your issue!
Solved it!.
