### ISSUE TITLE
Doc?

### ISSUE THREAD

**Issue by techker** [LeandroSQ/android-ble-made-easy#9]
seems like the doc link is dead?Is there an example app on how to use?

**Comment by LeandroSQ** [comment]
Hello there, thank you for the interest in the project, I appreciate it!
You are right, unfortunally the dokka generated doc action is not working anymore, I will investigate it.

As for the example, on the source code you will find an application with the common scenarios covered
[Link](https://github.com/LeandroSQ/android-ble-made-easy/tree/master/app)

**Comment by LeandroSQ** [comment]
This is fixed by [Release v1.6.0](https://github.com/LeandroSQ/android-ble-made-easy/releases/tag/v1.6.0)
